/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WordGame;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Game game = new Game(new Masker(), new WordChooser());
        System.out.println("Welcome! Today the word to guess is:");

        while (game.counter > 0 && game.isGameWon() == false) {
            System.out.println(game.getWordToGuess());
            System.out.printf("Turns remaining: %d Enter a character: %n", game.counter);

            Scanner scanner = new Scanner(System.in);
            Character guess = scanner.nextLine().charAt(0);
            if (game.guessLetter(guess) == true) {
                System.out.println("You guessed correct!");
            } else {
                System.out.println("You guessed incorrect!");
            }
            scanner.close();

        }
        if (game.isGameLost()) {
            System.out.println("You lost");
        } else {
            System.out.println("You win");
        }
    }
}
