/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PriceLabel;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void appReturnsPrice() {
        App classUnderTest = new App();
        assertEquals("The price for Coffee Machine is 15.99", classUnderTest.getPriceLabel("Coffee Machine", 15.99));
    }
}
